#!/usr/bin/env bash

##### binary behavior
COMMAND=$1
COMMAND_ARG=$2
USE_CONFIG_FILE=false
FORCE=false
VALIDATOR_LOOPS=5
#####

##### network info
CHAIN_ID=""
NETWORK_ID=""
FORK_VERSION="0x60000069"
#####

##### default client values

# for Apple M1s
if [ "$(uname -s)" == "Darwin" ] && [ "$(uname -m)" == "arm64" ]
then
ARCHITECTURE="amd64"
else
ARCHITECTURE=$(uname -m)
ARCHITECTURE=${ARCHITECTURE/x86_64/amd64}
ARCHITECTURE=${ARCHITECTURE/aarch64/arm64}
fi
readonly os_arch_suffix="$(uname -s | tr '[:upper:]' '[:lower:]')-$ARCHITECTURE"

PLATFORM=""
case "$OSTYPE" in
darwin*) PLATFORM="darwin" ;;
linux*) PLATFORM="linux" ;;
msys*) PLATFORM="windows" ;;
cygwin*) PLATFORM="windows" ;;
*) exit 1 ;;
esac
readonly PLATFORM

if [ "$PLATFORM" == "windows" ]; then
    ARCHITECTURE="amd64.exe"
elif [[ "$os_arch_suffix" == *"arm64"* ]]; then
    ARCHITECTURE="arm64"
fi

if [[ "$ARCHITECTURE" == "armv7l" ]]; then
    color "31" "32-bit ARM is not supported. Please install a 64-bit operating system."
    exit 1
fi

LUKSO_SCRIPT_VERSION="v1.7.10"

RUN_DATE=$(date '+%Y-%m-%d__%H-%M-%S')
NETWORK="l15-prod"
IS_VALIDATOR=false
RUN_LUKSO_STATUS=false
PAN_ETHSTATS="S2qDE8rYtFVVGZ@stats.pandora.l15.lukso.network"
VAN_ETHSTATS="34.141.156.125:9090"
COINBASE=""

if [[ "$PLATFORM" == "linux" ]]; then
  LUKSO_HOME="$HOME/.lukso"
fi

if [[ "$PLATFORM" == "darwin" ]]; then
  LUKSO_HOME="$HOME/Library/LUKSO"
fi

DATADIR="$LUKSO_HOME/$NETWORK/datadirs"
LOGSDIR="$LUKSO_HOME/$NETWORK/logs"
NODE_NAME="$(LC_CTYPE=C LANG=C tr -dc A-F0-9 </dev/urandom | head -c 8)"
EXTERNAL_IP=$(curl -s ident.me)

###### General variables
HTTP_CONNECTIVITY=false
VANGUARD_RPC="127.0.0.1:4000"
######



SECONDS_PER_SLOT=6


###### Pandora settings
PANDORA_PORT="30405"
PANDORA_BOOTNODES=""
PANDORA_HTTP_ADDR="127.0.0.1"
PANDORA_HTTP_PORT="8545"
PANDORA_WS_ADDR="127.0.0.1"
PANDORA_WS_PORT="8546"
PANDORA_METRICS=false
PANDORA_NODEKEY=""
PANDORA_VERBOSITY=info
PAN_WS_MINER_NOTIFY="ws://127.0.0.1:7878"
PAN_HTTP_MINER_NOTIFY="http://127.0.0.1:7877"
CORS_DOMAIN=""
######

###### Vanguard
VANGUARD_VERBOSITY=info
VANGUARD_HTTP_WEB3PROVIDER="http://127.0.0.1:8545"
VANGUARD_RPC_HOST="127.0.0.1"
VANGUARD_BOOTNODES=""
VANGUARD_P2P_PRIV_KEY=""
VANGUARD_P2P_HOST_DNS=""
VANGUARD_RPC_PORT="4000"
VANGUARD_UDP_PORT="12000"
VANGUARD_TCP_PORT="13000"
VANGUARD_GRPC_GATEWAY_PORT="3500"
VANGUARD_MONITORING_HOST="127.0.0.1"
VANGUARD_MONITORING_PORT="8080"
VAN_MIN_SYNC_PEERS="2"
VAN_MAX_P2P_PEERS="50"
VAN_ETHSTATS_METRICS="http://$VANGUARD_MONITORING_HOST:$VANGUARD_MONITORING_PORT/metrics"
######

###### Validator
KEYS_DIR="$LUKSO_HOME/$NETWORK"
WALLET_DIR="$LUKSO_HOME/$NETWORK/vanguard_wallet"
VALIDATOR_PASSWORD_FILE=""
VALIDATOR_VERBOSITY=info
VALIDATOR_BEACON_RPC_PROVIDER=$VANGUARD_RPC
VALIDATOR_PANDORA_HTTP_PROVIDER="http://127.0.0.1:8545"
######

###### Eth2Stats
ETH2STATS_BEACON_ADDR=$VANGUARD_RPC
######

###### for config tool
CONFIG_DATA=()
######

function parse_yaml() {
  local prefix=""
  local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @ | tr @ '\034')
  LC_CTYPE=C LANG=C sed -ne "s|^\($s\):|\1|" \
    -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
    -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" $1 |
    awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

parse_config() {
  eval $(parse_yaml $1)
}

download() {
  URL="$1"
  LOCATION="$2"
  if [[ $PLATFORM == "linux" ]]; then
    if ! wget -q --spider "$URL"; then
      echo "File not found, check URL: $URL"
      exit
    fi
    sudo wget -O $LOCATION $URL
  fi

  if [[ $PLATFORM == "darwin" ]]; then
    STATUS_CODE=$(curl -L -s -o /dev/null -I -w "%{http_code}" $URL)
    if [[ $STATUS_CODE != "200" ]]; then
      echo "File not found, check URL: $URL"
      exit
    fi
    sudo curl -o $LOCATION -Lk $URL
  fi
}

download_binary() {
  CLIENT="$1"
  TAG="$2"

  case $CLIENT in

  geth)
    REPO="go-ethereum"
    ;;

  beacon-chain)
    REPO="prysm"
    ;;

  network-validator-tools)
    REPO="network-validator-tools"
    ;;

  validator)
    REPO="prysm"
    ;;

  eth2stats-client)
    REPO="network-vanguard-stats-client"
    ;;

  esac

  mkdir -p /opt/lukso/binaries/$CLIENT/$TAG
  download https://github.com/lukso-network/"$REPO"/releases/download/$TAG/$CLIENT-$TAG-$PLATFORM-$ARCHITECTURE /opt/lukso/binaries/$CLIENT/$TAG/$CLIENT-$PLATFORM-$ARCHITECTURE
  sudo chmod +x /opt/lukso/binaries/$CLIENT/$TAG/$CLIENT-$PLATFORM-$ARCHITECTURE
}

bind_binary() {
  CLIENT="$1"
  TAG="$2"
  if [[ ! -f /opt/lukso/binaries/$CLIENT/$TAG/$CLIENT-$PLATFORM-$ARCHITECTURE ]]; then
    download_binary $CLIENT $TAG
  fi

  sudo ln -sf "/opt/lukso/binaries/$CLIENT/$TAG/$CLIENT-$PLATFORM-$ARCHITECTURE" /usr/local/bin/$CLIENT
}

bind_binaries() {
  echo
}

generate_deposit_data() {
  read -p "Where to store deposit keys? Default: [$KEYS_DIR] " INPUT
  if [[ -n "$INPUT" ]]; then
    KEYS_DIR=$INPUT
  fi
  eval KEYS_DIR=$KEYS_DIR
  mkdir -p $KEYS_DIR
  read -p "How many validators? (Cost for 1 validator = 32 LYXt): " VALIDATORS_NUMBER
  echo "Running lukso-deposit-cli..."

  VALIDATOR_MNEMONIC=$(network-validator-tools mnemonic)
  read -p "Enter Validator mnemonic file location. Keep blank to generate atutomatically" INPUT
  if [[ -n "$INPUT" ]]; then
    VALIDATOR_MNEMONIC=`cat $INPUT`
  fi
  echo "SAVE THIS VALIDATOR MNEMONIC FOR FUTURE USAGE: ${VALIDATOR_MNEMONIC}"

  WITHDRAWAL_MNEMONIC=$(network-validator-tools mnemonic)
  read -p "Enter Validator mnemonic file location. Keep blank to generate atutomatically" INPUT
  if [[ -n "$INPUT" ]]; then
    WITHDRAWAL_MNEMONIC=`cat $INPUT`
  fi
  echo "SAVE THIS WITHDRAWAL MNEMONIC FOR FUTURE USAGE: ${WITHDRAWAL_MNEMONIC}"


  network-validator-tools deposit-data \
    --fork-version=${FORK_VERSION} \
    --source-min=0 \
    --source-max=${VALIDATORS_NUMBER} \
    --validators-mnemonic="${VALIDATOR_MNEMONIC}" \
    --withdrawals-mnemonic="${WITHDRAWAL_MNEMONIC}" > "$KEYS_DIR/deposit-data.json"
}

generate_keystore() {

  if [[ ! -d $WALLET_DIR ]]; then
    echo "Creating new keystore"
    mkdir -p $WALLET_DIR
  fi

  if [[ -z $OVERRIDE_WALLET_DIR ]]; then
    read -p "Enter keystore location? Default: [$WALLET_DIR] " INPUT
    eval INPUT="$INPUT"
      if [[ -n "$INPUT" ]]; then
        WALLET_DIR=$INPUT
      fi
  fi

  read -p -s "Enter your keystore password: " KEYSTORE_PASSWORD
  if [[ -z $KEYSTORE_PASSWORD ]]; then
    echo "Enter a valid keystore password"
    exit 1
  fi

  read -p "How many validators? (Cost for 1 validator = 32 LYXt): " VALIDATORS_NUMBER

  VALIDATOR_MNEMONIC=$(network-validator-tools mnemonic)
  read -p "Enter Validator mnemonic file location. Keep blank to generate atutomatically" INPUT
  if [[ -n "$INPUT" ]]; then
    VALIDATOR_MNEMONIC=`cat $INPUT`
  fi
  echo "SAVE THIS VALIDATOR MNEMONIC FOR FUTURE USAGE: ${VALIDATOR_MNEMONIC}"

  network-validator-tools keystores
    --insecure \
    --prysm-pass=${KEYSTORE_PASSWORD} \
    --source-min=0 \
    --source-max=${VALIDATORS_NUMBER} \
    --source-mnemonic=${VALIDATOR_MNEMONIC} \
    --out-loc=${WALLET_DIR}
}

parse_config_field() {
  VALUE="$1"
  DEFAULT="$3"
  LABEL="$2 [default: $DEFAULT]: "
  read -p "$LABEL" INPUT
  eval INPUT="$INPUT"
  if [[ -z "$INPUT" ]]; then
    echo -e "\033[1A\033[2K$LABEL<Using default>"
    CONFIG_DATA+=("$VALUE: \"$DEFAULT\"")
  else
    CONFIG_DATA+=("$VALUE: \"$INPUT\"")
  fi
}

setup_config() {
  clear
  echo "This tool will create config file to be used with node."
  echo "Enter desired value or leave it empty to use default."
  echo "For paths you can use variables like \$PWD or \".\" as they will be resolved"
  echo

  mkdir -p "$LUKSO_HOME/$NETWORK"
  DEFAULT="$LUKSO_HOME/$NETWORK/config.yaml"
  LABEL="Config file location [default: $DEFAULT]: "
  read -p "$LABEL" CONFIG_LOCATION
  eval CONFIG_LOCATION="$CONFIG_LOCATION"
  if [[ -z "$CONFIG_LOCATION" ]]; then
    echo -e "\033[1A\033[2K$LABEL<Using default>"
    CONFIG_LOCATION="$DEFAULT"
  fi

  parse_config_field "COINBASE" "Enter your coinbase:" "0x616e6f6e796d6f75730000000000000000000000"
  parse_config_field "WALLET_DIR" "Type wallet location:" "$LUKSO_HOME/$NETWORK/vanguard_wallet"
  parse_config_field "DATADIR" "Type data directory (chain will be stored there) location:" "$LUKSO_HOME/$NETWORK/datadirs"
  parse_config_field "LOGSDIR" "Type logs location:" "$LUKSO_HOME/$NETWORK/logs"
  parse_config_field "NODE_NAME" "Type name of the node:" "$NETWORK-$NODE_NAME"

  echo "Saving config to $CONFIG_LOCATION"
  printf '%s\n' "${CONFIG_DATA[@]}" >|"$CONFIG_LOCATION"
}

download_network_config() {
  NETWORK=$1
  # TODO: CHANGE DOWNLOAD ADDRESS
  CDN="https://storage.googleapis.com/l15-cdn/networks/$NETWORK"
  sudo mkdir -p /opt/lukso/networks/$NETWORK/config
  TARGET=/opt/lukso/networks/$NETWORK/config
  download $CDN/network-config.yaml?ignoreCache=1 $TARGET/network-config.yaml
  download $CDN/pandora-genesis.json?ignoreCache=1 $TARGET/geth-genesis.json
  download $CDN/vanguard-genesis.ssz?ignoreCache=1 $TARGET/beacon-genesis.ssz
  download $CDN/vanguard-config.yaml?ignoreCache=1 $TARGET/beacon-config.yaml
  download $CDN/pandora-nodes.json?ignoreCache=1 $TARGET/geth-nodes.json
}

pick_network() {
  NETWORK=$1
  if [[ ! -d /opt/lukso/networks/"$NETWORK" ]]; then
    download_network_config $NETWORK
  fi
}

check_validator_requirements() {
  CAN_VALIDATE=true
  eval WALLET_DIR="$WALLET_DIR"

  if [[ $COMMAND_ARG != "validator" ]] && [[ ! -n $COINBASE ]]; then
    echo "Please provide coinbase: --coinbase 0x<ETH1_ADDRESS>"
    exit
  fi

  if [[ $COMMAND_ARG == "validator" ]] && [[ ! -n $COINBASE ]]; then
    if [[ ! $(geth attach $DATADIR/geth/geth.ipc --exec "eth.coinbase") =~ ^\"0x[a-fA-F0-9]{40}\"$ ]]; then
      echo "ERROR: Coinbase is not set on already running pandora. Please provide it using:"
      echo "--coinbase 0x<ETH1_ADDRESS>"
      CAN_VALIDATE=false
    fi
  fi

  if [[ ! -d $WALLET_DIR ]]; then
    echo "Cannot validate, wallet not found. Your wallet directory is: $WALLET_DIR"
    echo "Create new wallet using \"lukso keystore\" "
    CAN_VALIDATE=false
    exit
  fi

  if [[ -n $VALIDATOR_PASSWORD_FILE ]] && [[ ! -f $VALIDATOR_PASSWORD_FILE ]]; then
    echo "Cannot validate, password file not found"
    CAN_VALIDATE=false
  fi

  if [[ "$CAN_VALIDATE" == "false" ]]; then
    exit 1
  fi

   if [[ ! -n $VALIDATOR_PASSWORD_FILE ]]; then
    PASSWORD_CHECK=1
    while [[ $PASSWORD_CHECK != 0 ]]; do
      read -p "Enter validator password: " -s INPUT
      echo
      TEMPPASSFILE=$(mktemp)
      echo -n $INPUT > $TEMPPASSFILE
      validator accounts list --wallet-dir="$WALLET_DIR/prysm" --wallet-password-file=$TEMPPASSFILE &> /dev/null
      PASSWORD_CHECK=$?
      if [[ $PASSWORD_CHECK != 0 ]]; then
        echo "WRONG PASSWORD for wallet in $WALLET_DIR"
      fi
    done
  fi

}


start_geth() {

  case $PANDORA_VERBOSITY in
  silent)
    PANDORA_VERBOSITY=0
    ;;
  error)
    PANDORA_VERBOSITY=1
    ;;
  warn)
    PANDORA_VERBOSITY=2
    ;;
  info)
    PANDORA_VERBOSITY=3
    ;;
  debug)
    PANDORA_VERBOSITY=4
    ;;
  detail|trace)
    PANDORA_VERBOSITY=5
    ;;
  esac

  mkdir -p "$LOGSDIR"/geth
  echo -n $RUN_DATE >|"$LOGSDIR"/geth/current.tmp
  if [[ ! -d "$DATADIR/geth" ]]; then
    mkdir -p "$DATADIR/geth"
  fi

  geth --datadir $DATADIR/geth init /opt/lukso/networks/$NETWORK/config/geth-genesis.json &>/dev/null
  cp /opt/lukso/networks/"$NETWORK"/config/geth-nodes.json $DATADIR/geth/geth/static-nodes.json

  ARGUMENTS=(
    "--datadir=$DATADIR/geth"
    "--networkid=$NETWORK_ID"
    "--port=$PANDORA_PORT"
    "--catalyst"
    "--bootnodes=$PANDORA_BOOTNODES"
    "--miner.gaslimit=80000000"
    "--verbosity=$PANDORA_VERBOSITY"
    "--http"
    "--http.addr=$PANDORA_HTTP_ADDR"
    "--http.port=$PANDORA_HTTP_PORT"
    "--ws"
    "--ws.addr=$PANDORA_WS_ADDR"
    "--ws.port=$PANDORA_WS_PORT"
    "--miner.notify=$PAN_WS_MINER_NOTIFY,$PAN_HTTP_MINER_NOTIFY"
  )


  if [[ $COINBASE ]]; then
    MINER_ARGUMENTS=(
      "--mine"
      "--miner.etherbase=$COINBASE"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${MINER_ARGUMENTS[@]}")
  fi

  if [[ $PANDORA_UNIVERSAL_PROFILE_EXPOSE ]] && [[ ! $PANDORA_UNSAFE_EXPOSE ]] && [[ $HTTP_CONNECTIVITY == "true" ]]; then
    API_ARGUMENTS=(
      "--http.api=net,eth,txpool,web3"
      "--ws.api=net,eth,txpool,web3"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${API_ARGUMENTS[@]}")
  fi

  if [[ $PANDORA_UNSAFE_EXPOSE ]] && [[ $HTTP_CONNECTIVITY == "true" ]]; then
    API_ARGUMENTS=(
      "--http.api=admin,net,eth,debug,miner,personal,txpool,web3"
      "--ws.api=admin,net,eth,debug,miner,personal,txpool,web3"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${API_ARGUMENTS[@]}")
  fi

  if [[ -n $CORS_DOMAIN ]] && [[ $HTTP_CONNECTIVITY == "true" ]]; then
    CORS_DOMAIN_FLAGS=(
      "--http.corsdomain=$CORS_DOMAIN"
      "--ws.origins=$CORS_DOMAIN"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${CORS_DOMAIN_FLAGS[@]}")
  fi

  if [[ -n $OVERRIDE_PANDORA_EXTERNAL_IP ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--nat=extip:$OVERRIDE_PANDORA_EXTERNAL_IP")
  else
    ARGUMENTS=("${ARGUMENTS[@]}" "--nat=extip:$EXTERNAL_IP")
  fi

  if $PANDORA_METRICS || $RUN_LUKSO_STATUS; then
    METRICS_FLAGS=(
      "--metrics"
      "--metrics.expensive"
      "--pprof"
      "--pprof.addr=127.0.0.1"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${METRICS_FLAGS[@]}")
  fi

  if [[ -n $PANDORA_NODEKEY ]]; then
    NODEKEY_FLAGS=(
      "--nodekey=$PANDORA_NODEKEY"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${NODEKEY_FLAGS[@]}")
  fi

  if [[ -n $PANDORA_RPCVHOSTS ]] && [[ $HTTP_CONNECTIVITY == "true" ]]; then
    RPCVHOSTS_FLAGS=(
      "--http.vhosts=$PANDORA_RPCVHOSTS"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${RPCVHOSTS_FLAGS[@]}")
  fi

  if [[ -n $PAN_ETHSTATS ]]; then
    ETHSTATS_FLAG=(
      "--ethstats=$NODE_NAME:$PAN_ETHSTATS"
    )
    ARGUMENTS=("${ARGUMENTS[@]}" "${ETHSTATS_FLAG[@]}")
  fi

  nohup geth \
    "${ARGUMENTS[@]}" \
    >|$LOGSDIR/geth/geth_"$RUN_DATE".log 2>&1 &
  disown
}

start_beacon() {
  mkdir -p "$LOGSDIR"/beacon-chain
  echo -n $RUN_DATE >|"$LOGSDIR"/beacon-chain/current.tmp
  VANGUARD_BOOTNODES=(${VANGUARD_BOOTNODES//,/ })
  BOOTNODES_ARGS=()
  for n in "${VANGUARD_BOOTNODES[@]}"; do
    BOOTNODES_ARGS+=("--bootstrap-node=$n")
  done
  ARGUMENTS=(
    "--accept-terms-of-use"
    "--kintsugi-testnet"
    "--genesis-state=/opt/lukso/networks/$NETWORK/config/beacon-genesis.ssz"
    "--datadir=$DATADIR/beacon-chain/"
    "--chain-config-file=/opt/lukso/networks/$NETWORK/config/beacon-config.yaml"
    "${BOOTNODES_ARGS[@]}"
    "--deposit-contract=0x000000000000000000000000000000000000cafe"
    "--contract-deployment-block=0"
    "--verbosity=$VANGUARD_VERBOSITY"
    "--min-sync-peers=$VAN_MIN_SYNC_PEERS"
    "--p2p-max-peers=$VAN_MAX_P2P_PEERS"
    "--p2p-udp-port=$VANGUARD_UDP_PORT"
    "--p2p-tcp-port=$VANGUARD_TCP_PORT"
    "--grpc-gateway-port=$VANGUARD_GRPC_GATEWAY_PORT"
    "--update-head-timely"
    "--rpc-host=$VANGUARD_RPC_HOST"
    "--rpc-port=$VANGUARD_RPC_PORT"
    "--http-web3provider=$VANGUARD_HTTP_WEB3PROVIDER"
    "--monitoring-host=$VANGUARD_MONITORING_HOST"
    "--monitoring-port=$VANGUARD_MONITORING_PORT"
  )


  if [[ -n $VANGUARD_P2P_PRIV_KEY ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--p2p-priv-key=$VANGUARD_P2P_PRIV_KEY")
  fi

  if [[ -n $VANGUARD_P2P_HOST_DNS ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--p2p-host-dns=$VANGUARD_P2P_HOST_DNS")
  elif [[ -n $OVERRIDE_VANGUARD_EXTERNAL_IP ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--p2p-host-ip=$OVERRIDE_VANGUARD_EXTERNAL_IP")
  else
    ARGUMENTS=("${ARGUMENTS[@]}" "--p2p-host-ip=$EXTERNAL_IP")
  fi

  nohup beacon-chain \
    "${ARGUMENTS[@]}" \
    >|$LOGSDIR/beacon-chain/beacon-chain_"$RUN_DATE".log 2>&1 &
  disown
}

start_validator() {

  if [[ $COMMAND_ARG == "validator" ]] && [[ $COINBASE ]]; then
    geth attach $DATADIR/geth/geth.ipc --exec "miner.setEtherbase(\"$COINBASE\")" > /dev/null
    geth attach $DATADIR/geth/geth.ipc --exec "miner.start()" > /dev/null
  fi

  mkdir -p "$LOGSDIR"/validator
  echo -n $RUN_DATE >|"$LOGSDIR"/validator/current.tmp

  ARGUMENTS=(
    "--datadir=$DATADIR/validator/"
    "--accept-terms-of-use"
    "--chain-config-file=/opt/lukso/networks/$NETWORK/config/beacon-config.yaml"
    "--verbosity=$VALIDATOR_VERBOSITY"
    "--wallet-dir=$WALLET_DIR/prysm"
    "--log-file=$LOGSDIR/validator/validator_$RUN_DATE.log"
  )

  if [[ -n $VALIDATOR_PASSWORD_FILE ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--wallet-password-file=$VALIDATOR_PASSWORD_FILE")
  fi

  if [[ -n $TEMPPASSFILE ]]; then
    ARGUMENTS=("${ARGUMENTS[@]}" "--wallet-password-file=$TEMPPASSFILE")
  fi

  nohup validator \
    "${ARGUMENTS[@]}" \
    >|$LOGSDIR/validator/validator_"$RUN_DATE".log 2>&1 &
  disown

  if [[ -n $TEMPPASSFILE ]]; then
    # Wait until validator starts
    TRIES=0
    while [[ $TRIES -lt VALIDATOR_LOOPS ]]; do
      sleep 1
      echo -n " . "
      TRIES=$((TRIES+1))
    done

    if [[ ! $(pgrep -x "validator") ]]; then
      echo "ERROR: Cannot start validator"
      exit
    fi

    echo -n "OK "
    echo

    rm $TEMPPASSFILE
  fi
}

start_eth2stats_client() {
  mkdir -p "$LOGSDIR"/eth2stats
  echo -n $RUN_DATE >|"$LOGSDIR"/eth2stats/current.tmp

  ARGUMENTS=(
    "--beacon.type=prysm"
    "--data.folder=$DATADIR/eth2stats-client"
    "--eth2stats.node-name=$NODE_NAME"
    "--eth2stats.addr=$VAN_ETHSTATS"
    "--eth2stats.tls=false"
    "--beacon.metrics-addr=$VAN_ETHSTATS_METRICS"
    "--beacon.addr=$ETH2STATS_BEACON_ADDR"
  )

  nohup eth2stats-client run \
    "${ARGUMENTS[@]}" \
    >|"$LOGSDIR"/eth2stats/eth2stats_"$RUN_DATE".log 2>&1 &
  disown
}

start_all() {
  if [[ "$IS_VALIDATOR" == true ]]; then
    check_validator_requirements
  fi

  echo "################# Starting pandora #######################"
  start_geth
  sleep 2

  echo "################# Starting beacon-chain #######################"
  start_beacon
  sleep 2

  if [[ "$IS_VALIDATOR" == true ]]; then
    echo "################# Starting validator #######################"
    start_validator
    sleep 2
  fi

  if [[ -n $VAN_ETHSTATS ]]; then
    echo "################# Starting eth2stats_client #######################"
    start_eth2stats_client
    sleep 2
  fi
}

start() {

  if [[ $# -eq 0 ]]; then
    ARGUMENT="all"
  else
    ARGUMENT=$1
  fi

  echo -n "Starting: "
  case $ARGUMENT in
  geth)
    echo "geth client"
    start_geth
    ;;
  beacon)
    echo "beacon-chain client"
    start_beacon
    ;;
  validator)
    echo "validator client"
    check_validator_requirements
    start_validator
    ;;
  eth2stats)
    echo "eth2stats client"
    start_eth2stats_client
    ;;
  *)
    echo "ALL clients"
    start_all
    ;;
  esac
}

stop_geth() {
  echo -n "Stopping geth client... "
  if [[ "$FORCE" == true ]]; then
    echo "[FORCE]"
    sudo kill -9 $(sudo lsof -t -i:30405) &>/dev/null
    sleep 1
  else
    echo
    sudo kill $(sudo lsof -t -i:30405) &>/dev/null
    sleep 1
  fi
}

stop_beacon() {
  echo -n "Stopping beacon-chain client... "

  if [[ "$FORCE" == true ]]; then
    echo "[FORCE]"
    sudo kill -9 $(sudo lsof -t -i:4000) &>/dev/null
    sleep 1
    sudo kill -9 $(sudo lsof -t -i:12000) &>/dev/null
    sleep 1
    sudo kill -9 $(sudo lsof -t -i:13000) &>/dev/null
    sleep 1
  else
    echo
    sudo kill $(sudo lsof -t -i:4000) &>/dev/null
    sleep 1
    sudo kill $(sudo lsof -t -i:12000) &>/dev/null
    sleep 1
    sudo kill $(sudo lsof -t -i:13000) &>/dev/null
    sleep 1
  fi
}

stop_validator() {
  echo -n "Stopping validator client... "
  if [[ "$FORCE" == true ]]; then
    echo "[FORCE]"
    sudo kill -9 $(sudo lsof -t -i:7000) &>/dev/null
    sleep 1
  else
    echo
    sudo kill $(sudo lsof -t -i:7000) &>/dev/null
    sleep 1
  fi
}

stop_eth2stats_client() {
  echo -n "Stopping eth2stats client... "
  if [[ "$FORCE" == true ]]; then
    echo "[FORCE]"
    sudo pkill -9 "eth2stats-client*"
    sleep 1
  else
    echo
    sudo pkill "eth2stats-client*"
    sleep 1
  fi
}

stop_all() {
  stop_validator &
  stop_beacon &
  stop_geth &
  stop_eth2stats_client
}

stop() {

  if [[ $# -eq 0 ]]; then
    ARGUMENT="all"
  else
    ARGUMENT=$1
  fi

  if [[ "$FORCE" == true ]]; then
    read -p "This may result in node data corruption. Continue? (Y/n) " var
    if [[ "$var" != "Y" ]]; then
      echo "Exiting without effect..."
      exit 0
    fi
  fi
  case "$ARGUMENT" in
  geth)
    stop_geth
    ;;
  beacon)
    stop_beacon
    ;;
  validator)
    stop_validator
    ;;
  eth2stats)
    stop_eth2stats_client
    ;;
  *)
    stop_all
    ;;
  esac
}

reset_geth() {
  rm -rf $DATADIR/geth
}

reset_beacon() {
  rm -rf $DATADIR/beacon-chain
}

reset_validator() {
  rm -rf $DATADIR/validator
}

reset_eth2stats_client() {
  rm -rf $DATADIR/eth2stats-client
}

reset_all() {
  reset_geth
  reset_beacon
  reset_validator
  reset_eth2stats_client
}

reset() {

  if [[ $# -eq 0 ]]; then
    ARGUMENT="none"
  else
    ARGUMENT=$1
  fi

  case "$ARGUMENT" in
  geth)
    reset_geth
    ;;
  beacon)
    reset_beacon
    ;;
  validator)
    reset_validator
    ;;
  eth2stats)
    reset_eth2stats_client
    ;;
  all)
    reset_all
    ;;
  *)
    echo "Choose a client: [geth, beacon, validator, all] "
    ;;
  esac
}

help() {
  echo "USAGE:"
  echo "lukso <command> [argument] [--flags]"
  echo
  echo "Available commands with arguments:"
  echo "start         Starts up all or specific client(s)"
  echo "               [geth, beacon, validator, eth2stats-client, all]"
  echo
  echo "stop          Stops all or specific client(s)"
  echo "               [geth, beacon, validator, eth2stats-client, all]"
  echo
  echo "reset         Clears client(s) datadirs (this also removes chain-data) 	"
  echo "               [geth, beacon, validator, all, none]"
  echo
  echo "config        Interactive tool for creating config file"
  echo
  echo "gen-deposit-data        generates deposit-data.json"
  echo
  echo "keystore        generates merge keystore"
  echo
  echo "logs          Shows logs"
  echo "               [geth, beacon, validator, eth2stats-client]"
  echo
  echo "attach        Attaches to geth console via IPC socket (use with --datadir if not default). You cannot reach remote HTTP or WS via this command"
  echo
  echo "bind-binaries sets client(s) to desired version, use with flags for setting tag: --geth v0.2.0-rc.1, --beacon v0.2.0-rc.1, --validator v0.2.0-rc.1"
  echo
  echo
  echo "Available commands without arguments:"
  echo "version        Shows the LUKSO script version"
  echo
  echo
  echo "Available flags:"
  echo "--network              Picks config collection to be used (and downloads if it doesn't exist)"
  echo "                       [l15-prod, l15-staging, l15-dev]"
  echo
  echo "--l15-prod             Alias for --network l15-prod"
  echo
  echo "--l15-staging          Alias for --network l15-staging"
  echo
  echo "--l15-dev              Alias for --network l15-dev"
  echo
  echo "--config               Path to config file"
  echo "                       [config.yaml]"
  echo
  echo "--datadir              Sets datadir path"
  echo "                       [Ex. /mnt/external/lukso-datadir]"
  echo
  echo "--logsdir              Sets logs path"
  echo "                       [Ex. /mnt/external/lukso-logs]"
  echo
  echo "--home                 Sets path for datadir and logs in a single location (--datadir and --logs take priority)"
  echo "                       [Ex. /var/lukso]"
  echo
  echo "--validate             Starts validator"
  echo
  echo "--coinbase             Sets pandora coinbase"
  echo "                       [ETH1 address ex. 0x616e6f6e796d6f75730000000000000000000777]"
  echo
  echo "--node-name            Name of node that's shown on geth stats and beacon-chain stats"
  echo "                       [String ex. johnsmith123]"
  echo
  echo "--deposit              Sets lukso-deposit-cli tag to be used"
  echo "                       [Tag name ex. v0.2.0-rc.1]"
  echo
  echo "--eth2stats            Sets eth2stats tag to be used"
  echo "                       [Tag name ex. v0.2.0-rc.1]"
  echo
  echo "--geth                 Sets pandora tag to be used"
  echo "                       [Tag name ex. v0.2.0-rc.1]"
  echo
  echo "--geth-verbosity       Sets geth logging depth (note: geth uses integers for that flag, script will convert those to proper values)"
  echo "                       [silent, error, warn, info, debug, trace]"
  echo
  echo "--geth-bootnodes       Sets geth bootnodes"
  echo "                       [Strings of bootnodes separated by commas: \"enode://72caa...,enode://b4a11a...\"]"
  echo
  echo "--geth-http-port       geth client http port exposed. (default:  8545)"
  echo
  echo "--geth-metrics         Enables geth metrics server"
  echo
  echo "--geth-nodekey         P2P node key file"
  echo "                       [Path to file (relative or absolute)]"
  echo
  echo "--geth-rpcvhosts       Sets geth rpc virtual hosts (use quotes if you want to set * (\"*\") otherwise shell will resolve it"
  echo "                       [RPC vhosts]"
  echo
  echo "--geth-external-ip     Sets external IP for geth (overrides --external-ip if present)"
  echo "                       [72.122.32.234]"
  echo
  echo "--geth-universal-profile-expose  Exposes \"net,eth,txpool,web3\" API's on geth "
  echo
  echo "--geth-unsafe-expose  Exposes \"admin,net,eth,debug,miner,personal,txpool,web3\" API's on geth"
  echo
  echo "--geth-port                           Geth client TCP/UDP port exposed. (default:  30405)"
  echo
  echo "--geth-http-addr                      Geth client http address exposed. (default:  127.0.0.1)"
  echo
  echo "--geth-ws-addr                        Geth client websocket address exposed. (default:  127.0.0.1)"
  echo
  echo "--geth-ws-port                        Geth client websocket port exposed. (default:  8546)"
  echo
  echo "--geth-http-miner-addr                [Requires --http-connectivity] Geth HTTP URL to notify of new work packages. (default:  http://127.0.0.1:7877)"
  echo
  echo "--geth-ws-miner-addr                  [Requires --http-connectivity] Geth Websocket URL to notify of new work packages. (default:  ws://127.0.0.1:7878)"
  echo
  echo "--geth-ethstats                       Geth flag to activate ethstats listing on remote dashboard. If enabled you should see your node by your node name provided via --node-name flag or lukso config. Example: --geth-ethstats token123@stats.example.com. (default:  enabled for l15 testnet)"
  echo
  echo "--beacon              Sets beacon-chain tag to be used"
  echo "                       [Tag name ex. v0.2.0-rc.1]"
  echo
  echo "--beacon-verbosity    Sets beacon-chain logging depth"
  echo "                       [silent, error, warn, info, debug, trace]"
  echo
  echo "--beacon-bootnodes    Sets beacon-chain bootnodes"
  echo "                       [Strings of bootnodes separated by commas: \"enr:-Ku4QAmY...,enr:-M23QLmY...\"]"
  echo
  echo "--beacon-p2p-priv-key The file containing the private key to use in communications with other peers."
  echo "                       [Path to file (relative or absolute)]"
  echo
  echo "--beacon-external-ip  Sets external IP for beacon-chain (overrides --external-ip if present)"
  echo "                       [72.122.32.234]"
  echo
  echo "--beacon-p2p-host-dns Sets host DNS beacon-chain (overrides --external-ip AND --beacon-external-ip if present)"
  echo "                       [72.122.32.234]"
  echo
  echo "--beacon-monitoring-host Sets beacon-chain monitoring listening interface"
  echo "                       [IP, ex. 127.0.0.1]"
  echo
  echo "--beacon-monitoring-port Sets beacon-chain monitoring port"
  echo "                       [Port, ex. 8080]"
  echo
  echo "--validator            Sets validator tag to be used"
  echo "                       [Tag name ex. v0.2.0-rc.1]"
  echo
  echo "--validator-verbosity  Sets validator logging depth"
  echo "                       [silent, error, warn, info, debug, trace]"
  echo
  echo "--keys-dir             Sets directory of lukso-deposit-cli keys (can be used with \"keygen\" or \"wallet\")"
  echo "                       [Path, relative or absolute]"
  echo
  echo "--keys-password-file   Sets path to lukso-deposit-cli keys (can be used with \"keygen\" or \"wallet\")"
  echo "                       [Path, relative or absolute]"
  echo
  echo "--wallet-dir           Sets directory of lukso-validator wallet"
  echo "                       [Path, relative or absolute]"
  echo
  echo "--wallet-password-file Password for lukso-validator"
  echo "                       [Path to file]"
  echo
  echo "--cors-domain          Sets CORS domain (note: if you want to set every origin you must type asterisk wrapped in quotes '*' otherwise shell may try to resolve it"
  echo
  echo "--external-ip          Sets external IP for geth and beacon-chain"
  echo "                       [72.122.32.234]"
  echo
  echo "--genesis-time         Overrides network-config provided genesis time"
  echo "                       [1639667382]"
  echo
  echo "--seconds-per-slot     Overrides network-config provided seconds per slot value"
  echo "                       [6]"
  echo
  echo "--allow-respin         Deletes all datadirs IF network config changed (based on genesis time)"
  echo
  echo "--force                Enables force mode for stopping"
  echo
  echo "--http-connectivity                   Switches connectivity between clients from IPC to local HTTP - less secure! (default: uses IPC sockets path like: $DATADIR/pandora/geth.ipc, instead of http://127.0.0.1:8545 endpoint)"
  echo
  echo "--beacon-http-web3provider            An eth1 web3 provider string http endpoint or IPC socket path. (default: http://127.0.0.1:8545)"
  echo
  echo "--beacon-rpc-host                     [Requires --http-connectivity] Host on which the RPC server should listen. (default: 127.0.0.1)"
  echo
  echo "--beacon-rpc-port                     [Requires --http-connectivity] Port on which the RPC server should listen. (default: 4000)"
  echo
  echo "--beacon-udp-port                     beacon chain client UDP port. The port used by discv5. (default: 12000)"
  echo
  echo "--beacon-tcp-port                     beacon chain client TCP port. The port used by libp2p. (default: 13000)"
  echo
  echo "--beacon-grpc-gateway-port            beacon-chain gRPC gateway port. The port on which the gateway server runs on (default: 3500)"
  echo
  echo "--validator-beacon-rpc-provider       [Requires --http-connectivity] Beacon node RPC provider endpoint. (default: $VANGUARD_RPC)"
  echo
  echo "--validator-geth-http-provider        [Requires --http-connectivity] A pandora string rpc endpoint. This is our pandora client http endpoint. (default: http://127.0.0.1:8545)"
  echo
  echo "--eth2stats-beacon-addr               Beacon node endpoint address for eth2stats-client. (default: $VANGUARD_RPC)"
  echo
  echo "--beacon-ethstats                     beacon-chain flag to activate eth2stats listing on remote dashboard. If enabled you should see your node by your node name provided via --node-name flag or lukso config. Example: --beacon-ethstats 192.168.0.1:9090. (default:  enabled for l15 testnet)"
  echo
  echo "--beacon-min-sync-peers               The required number of valid beacon-chain peers to connect with before syncing. (default: 2)"
  echo
  echo "--beacon-max-p2p-peers                The max number of beacon-chain p2p peers to maintain. (default: 50)"
  echo
  echo "--beacon-ethstats-metrics             The metrics address for beacon-chain eth2stats-client service (default: http://127.0.0.1:8080/metrics)"
  echo
  echo "--status-page                         This flag is for lukso-status activation. With this service you can check your node status over web browser (default: disabled). Default web address is: http://127.0.0.1:8111"
  exit
}

logs() {
  case "$1" in
  geth)
    CLIENT="geth"
    ;;
  beacon)
    CLIENT="beacon-chain"
    ;;
  validator)
    CLIENT="validator"
    ;;
  eth2stats)
    CLIENT="eth2stats"
    ;;
  *)
    echo "SELECT one of the clients ex. geth"
    exit
    ;;
  esac
  CURRENT_RUN=$(<"$LOGSDIR"/"$CLIENT"/current.tmp)
  tail -f "$LOGSDIR"/"$CLIENT"/"$CLIENT"_"$CURRENT_RUN".log

}

if [[ "$1" != -* ]]; then
  COMMAND=$1
  shift
fi

if [[ "$1" != -* ]]; then
  COMMAND_ARG=$1
  shift
fi

optspec=":hv-:"
while getopts "$optspec" optchar; do
  case "${optchar}" in
  h)
    echo "usage: $0 [-v] [--loglevel[=]<value>]" >&2
    exit 2
    ;;
  -)
    case "${OPTARG}" in

    geth)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      bind_binary geth $val
      ;;

    beacon)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      bind_binary beacon-chain $val
      ;;

    validator)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      bind_binary validator $val
      ;;

    deposit)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      bind_binary network-validator-tools $val
      ;;

    eth2stats)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      bind_binary eth2stats-client $val
      ;;

    network)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      pick_network $val
      ;;

    home)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_LUKSO_HOME=$val
      ;;

    datadir)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_DATADIR=$val
      ;;

    keys-dir)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_KEYS_DIR=$val
      ;;

    keys-password-file)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_KEYS_PASSWORD_FILE=$val
      ;;

    wallet-dir)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_WALLET_DIR=$val
      ;;

    wallet-password-file)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_VALIDATOR_PASSWORD_FILE=$val
      ;;

    logsdir)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_LOGSDIR=$val
      ;;

    l15-prod)
      pick_network l15-prod
      ;;

    l15-staging)
      pick_network l15-staging
      ;;

    l15-dev)
      pick_network l15-dev
      ;;

    config)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      USE_CONFIG_FILE=true
      CONFIG_FILE_PATH="$val"
      ;;

    coinbase)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_COINBASE="$val"
      ;;

    node-name)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_NODE_NAME="$val"
      ;;

    validate)
      OVERRIDE_IS_VALIDATOR=true
      ;;

    beacon-ethstats)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_WITH_ETH2STATS=$val
      ;;

    geth-bootnodes)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_BOOTNODES=$val
      ;;

    geth-http-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_HTTP_PORT=$val
      ;;

    geth-metrics)
      OVERRIDE_PANDORA_METRICS=true
      ;;

    geth-nodekey)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_PANDORA_NODEKEY=$val
      ;;

    geth-external-ip)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_EXTERNAL_IP=$val
      ;;

    geth-universal-profile-expose)
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_UNIVERSAL_PROFILE_EXPOSE=true
      ;;

    geth-unsafe-expose)
      echo "🛑 Unsafe expose enabled! 🛑"
      echo "🛑 Your node may be vulnerable to attacks 🛑"
      OVERRIDE_PANDORA_UNSAFE_EXPOSE=true
      ;;

    geth-rpcvhosts)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_RPCVHOSTS=$val
      ;;

    geth-ethstats)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_WITH_ETH1STATS=$val
      ;;

    geth-verbosity)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_VERBOSITY=$val
      ;;

    beacon-bootnodes)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_BOOTNODES=$val
      ;;

    beacon-p2p-priv-key)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      eval OVERRIDE_VANGUARD_P2P_PRIV_KEY=$val
      ;;

    beacon-external-ip)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_EXTERNAL_IP=$val
      ;;

    beacon-p2p-host-dns)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_P2P_HOST_DNS=$val
      ;;

    beacon-verbosity)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_VERBOSITY=$val
      ;;

    beacon-http-web3provider)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_HTTP_WEB3PROVIDER=$val
      ;;

    beacon-rpc-host)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_RPC_HOST="$val"
      ;;

    beacon-min-sync-peers )
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VAN_MIN_SYNC_PEERS="$val"
      ;;

    beacon-max-p2p-peers)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VAN_MAX_P2P_PEERS=$val
      ;;

    beacon-ethstats-metrics)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VAN_ETHSTATS_METRICS=$val
      ;;

    geth-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_PORT=$val
      ;;

    geth-http-addr)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_HTTP_ADDR=$val
      ;;

    geth-ws-addr)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_WS_ADDR=$val
      ;;

    geth-ws-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PANDORA_WS_PORT=$val
      ;;

    geth-ws-miner-addr)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PAN_WS_MINER_NOTIFY=$val
      ;;

    geth-http-miner-addr)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_PAN_HTTP_MINER_NOTIFY=$val
      ;;

    beacon-rpc-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_RPC_PORT=$val
      ;;

    beacon-udp-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_UDP_PORT=$val
      ;;

    beacon-tcp-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_TCP_PORT=$val
      ;;

    beacon-grpc-gateway-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_GRPC_GATEWAY_PORT=$val
      ;;

    validator-beacon-rpc-provider)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VALIDATOR_BEACON_RPC_PROVIDER=$val
      ;;

    validator-geth-http-provider)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VALIDATOR_PANDORA_HTTP_PROVIDER=$val
      ;;

    eth2stats-beacon-addr)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_ETH2STATS_BEACON_ADDR=$val
      ;;

    beacon-monitoring-host)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_MONITORING_HOST="$val"
      ;;

    beacon-monitoring-port)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VANGUARD_MONITORING_PORT="$val"
      ;;

    validator-verbosity)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_VALIDATOR_VERBOSITY=$val
      ;;

    genesis-time)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_CUSTOM_GENESIS_TIME=$val
      ;;

    seconds-per-slot)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_SECONDS_PER_SLOT=$val
      ;;

    external-ip)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_EXTERNAL_IP=$val
      ;;

    cors-domain)
      val="${!OPTIND}"
      OPTIND=$(($OPTIND + 1))
      OVERRIDE_CORS_DOMAIN=$val
      ;;

    allow-respin)
      OVERRIDE_ALLOW_RESPIN=true
      ;;

    status-page)
      OVERRIDE_RUN_LUKSO_STATUS=true
      ;;

    http-connectivity)
      OVERRIDE_HTTP_CONNECTIVITY=true
      ;;

    force)
      FORCE=true
      ;;

    *)
      if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
        echo "Unknown option --${OPTARG}" >&2
      fi
      ;;
    esac
    ;;

  *)
    if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
      echo "Non-option argument: '-${OPTARG}'" >&2
    fi
    ;;
  esac
done

if [[ "$USE_CONFIG_FILE" == true ]]; then
  parse_config "$CONFIG_FILE_PATH"
fi

parse_config "/opt/lukso/networks/$NETWORK/config/network-config.yaml"

# Prepare custom genesis timestamp for genesis flag based on downloaded network-config value
CUSTOM_GENESIS_TIME=$(echo -n $GENESIS_TIME)

# Override config file
if [[ -n $OVERRIDE_COINBASE ]]; then
  COINBASE=$OVERRIDE_COINBASE
fi

if [[ -n $OVERRIDE_NODE_NAME ]]; then
  NODE_NAME=$OVERRIDE_NODE_NAME
fi

if [[ -n $OVERRIDE_IS_VALIDATOR ]]; then
  IS_VALIDATOR=$OVERRIDE_IS_VALIDATOR
fi

if [[ -n $OVERRIDE_PANDORA_BOOTNODES ]]; then
  PANDORA_BOOTNODES=$OVERRIDE_PANDORA_BOOTNODES
fi

if [[ -n $OVERRIDE_PANDORA_HTTP_PORT ]]; then
  PANDORA_HTTP_PORT=$OVERRIDE_PANDORA_HTTP_PORT
fi

if [[ -n $OVERRIDE_PANDORA_METRICS ]]; then
  PANDORA_METRICS=$OVERRIDE_PANDORA_METRICS
fi

if [[ -n $OVERRIDE_PANDORA_NODEKEY ]]; then
  PANDORA_NODEKEY=$OVERRIDE_PANDORA_NODEKEY
fi

if [[ -n $OVERRIDE_PANDORA_EXTERNAL_IP ]]; then
  PANDORA_EXTERNAL_IP=$OVERRIDE_PANDORA_EXTERNAL_IP
fi

if [[ -n $OVERRIDE_PANDORA_UNIVERSAL_PROFILE_EXPOSE ]]; then
  PANDORA_UNIVERSAL_PROFILE_EXPOSE=$OVERRIDE_PANDORA_UNIVERSAL_PROFILE_EXPOSE
fi

if [[ -n $OVERRIDE_PANDORA_UNSAFE_EXPOSE ]]; then
  PANDORA_UNSAFE_EXPOSE=$OVERRIDE_PANDORA_UNSAFE_EXPOSE
fi

if [[ -n $OVERRIDE_PANDORA_RPCVHOSTS ]]; then
  PANDORA_RPCVHOSTS=$OVERRIDE_PANDORA_RPCVHOSTS
fi

if [[ -n $OVERRIDE_WITH_ETH1STATS ]]; then
  PAN_ETHSTATS=$OVERRIDE_WITH_ETH1STATS
fi

if [[ -n $OVERRIDE_WITH_ETH2STATS ]]; then
  VAN_ETHSTATS=$OVERRIDE_WITH_ETH2STATS
fi

if [[ -n $OVERRIDE_PANDORA_VERBOSITY ]]; then
  PANDORA_VERBOSITY=$OVERRIDE_PANDORA_VERBOSITY
fi

if [[ -n $OVERRIDE_VANGUARD_BOOTNODES ]]; then
  VANGUARD_BOOTNODES=$OVERRIDE_VANGUARD_BOOTNODES
fi

if [[ -n $OVERRIDE_VANGUARD_P2P_PRIV_KEY ]]; then
  VANGUARD_P2P_PRIV_KEY=$OVERRIDE_VANGUARD_P2P_PRIV_KEY
fi

if [[ -n $OVERRIDE_VANGUARD_EXTERNAL_IP ]]; then
  VANGUARD_EXTERNAL_IP=$OVERRIDE_VANGUARD_EXTERNAL_IP
fi

if [[ -n $OVERRIDE_VANGUARD_P2P_HOST_DNS ]]; then
  VANGUARD_P2P_HOST_DNS=$OVERRIDE_VANGUARD_P2P_HOST_DNS
fi

if [[ -n $OVERRIDE_VANGUARD_VERBOSITY ]]; then
  VANGUARD_VERBOSITY=$OVERRIDE_VANGUARD_VERBOSITY
fi

if [[ -n $OVERRIDE_VALIDATOR_VERBOSITY ]]; then
  VALIDATOR_VERBOSITY=$OVERRIDE_VALIDATOR_VERBOSITY
fi

if [[ -n $OVERRIDE_EXTERNAL_IP ]]; then
  EXTERNAL_IP=$OVERRIDE_EXTERNAL_IP
fi

if [[ -n $OVERRIDE_LUKSO_HOME ]]; then
  LUKSO_HOME=$OVERRIDE_LUKSO_HOME
  DATADIR=$LUKSO_HOME/$NETWORK/datadirs
  LOGSDIR=$LUKSO_HOME/$NETWORK/logs
fi

if [[ -n $OVERRIDE_DATADIR ]]; then
  DATADIR=$OVERRIDE_DATADIR
fi

if [[ -n $OVERRIDE_VANGUARD_HTTP_WEB3PROVIDER ]]; then
  VANGUARD_HTTP_WEB3PROVIDER=$OVERRIDE_VANGUARD_HTTP_WEB3PROVIDER
fi

if [[ -n $OVERRIDE_VANGUARD_RPC_HOST ]]; then
  VANGUARD_RPC_HOST=$OVERRIDE_VANGUARD_RPC_HOST
fi

if [[ -n $OVERRIDE_VALIDATOR_BEACON_RPC_PROVIDER ]]; then
  VALIDATOR_BEACON_RPC_PROVIDER=$OVERRIDE_VALIDATOR_BEACON_RPC_PROVIDER
fi

if [[ -n $OVERRIDE_VALIDATOR_PANDORA_HTTP_PROVIDER ]]; then
  VALIDATOR_PANDORA_HTTP_PROVIDER=$OVERRIDE_VALIDATOR_PANDORA_HTTP_PROVIDER
fi

if [[ -n $OVERRIDE_ETH2STATS_BEACON_ADDR ]]; then
  ETH2STATS_BEACON_ADDR=$OVERRIDE_ETH2STATS_BEACON_ADDR
fi

if [[ -n $OVERRIDE_VANGUARD_MONITORING_HOST ]]; then
  VANGUARD_MONITORING_HOST=$OVERRIDE_VANGUARD_MONITORING_HOST
  VAN_ETHSTATS_METRICS="http://$VANGUARD_MONITORING_HOST:$VANGUARD_MONITORING_PORT/metrics"
fi

if [[ -n $OVERRIDE_VANGUARD_MONITORING_PORT ]]; then
  VANGUARD_MONITORING_PORT=$OVERRIDE_VANGUARD_MONITORING_PORT
  VAN_ETHSTATS_METRICS="http://$VANGUARD_MONITORING_HOST:$VANGUARD_MONITORING_PORT/metrics"
fi

if [[ -n $OVERRIDE_EXTERNAL_IP ]]; then
  EXTERNAL_IP=$OVERRIDE_EXTERNAL_IP
fi

if [[ -n $OVERRIDE_LOGSDIR ]]; then
  LOGSDIR=$LOGSDIR
fi

if [[ -n $OVERRIDE_KEYS_DIR ]]; then
  KEYS_DIR=$OVERRIDE_KEYS_DIR
fi

if [[ -n $OVERRIDE_KEYS_PASSWORD_FILE ]]; then
  KEYS_PASSWORD_FILE=$OVERRIDE_KEYS_PASSWORD_FILE
fi

if [[ -n $OVERRIDE_CORS_DOMAIN ]]; then
  CORS_DOMAIN=$OVERRIDE_CORS_DOMAIN
fi

if [[ -n $OVERRIDE_WALLET_DIR ]]; then
  WALLET_DIR=$OVERRIDE_WALLET_DIR
fi

if [[ -n $OVERRIDE_VALIDATOR_PASSWORD_FILE ]]; then
  VALIDATOR_PASSWORD_FILE=$OVERRIDE_VALIDATOR_PASSWORD_FILE
fi

if [[ -n $OVERRIDE_ALLOW_RESPIN ]]; then
  ALLOW_RESPIN=$OVERRIDE_ALLOW_RESPIN
fi

if [[ -n $OVERRIDE_PANDORA_PORT ]]; then
  PANDORA_PORT=$OVERRIDE_PANDORA_PORT
fi

if [[ -n $OVERRIDE_PANDORA_HTTP_ADDR ]]; then
  PANDORA_HTTP_ADDR=$OVERRIDE_PANDORA_HTTP_ADDR
fi

if [[ -n $OVERRIDE_PANDORA_HTTP_PORT ]]; then
  PANDORA_HTTP_PORT=$OVERRIDE_PANDORA_HTTP_PORT
fi

if [[ -n $OVERRIDE_PANDORA_WS_ADDR ]]; then
  PANDORA_WS_ADDR=$OVERRIDE_PANDORA_WS_ADDR
fi

if [[ -n $OVERRIDE_PANDORA_WS_PORT ]]; then
  PANDORA_WS_PORT=$OVERRIDE_PANDORA_WS_PORT
fi

if [[ -n $OVERRIDE_PAN_WS_MINER_NOTIFY ]]; then
  PAN_WS_MINER_NOTIFY=$OVERRIDE_PAN_WS_MINER_NOTIFY
fi

if [[ -n $OVERRIDE_PAN_HTTP_MINER_NOTIFY ]]; then
  PAN_HTTP_MINER_NOTIFY=$OVERRIDE_PAN_HTTP_MINER_NOTIFY
fi

if [[ -n $OVERRIDE_VANGUARD_RPC_PORT ]]; then
  VANGUARD_RPC_PORT=$OVERRIDE_VANGUARD_RPC_PORT
fi

if [[ -n $OVERRIDE_VANGUARD_UDP_PORT ]]; then
  VANGUARD_UDP_PORT=$OVERRIDE_VANGUARD_UDP_PORT
fi

if [[ -n $OVERRIDE_VANGUARD_TCP_PORT ]]; then
  VANGUARD_TCP_PORT=$OVERRIDE_VANGUARD_TCP_PORT
fi

if [[ -n $OVERRIDE_VANGUARD_GRPC_GATEWAY_PORT ]]; then
  VANGUARD_GRPC_GATEWAY_PORT=$OVERRIDE_VANGUARD_GRPC_GATEWAY_PORT
fi

if [[ -n $OVERRIDE_VAN_MIN_SYNC_PEERS ]]; then
  VAN_MIN_SYNC_PEERS=$OVERRIDE_VAN_MIN_SYNC_PEERS
fi

if [[ -n $OVERRIDE_VAN_MAX_P2P_PEERS ]]; then
  VAN_MAX_P2P_PEERS=$OVERRIDE_VAN_MAX_P2P_PEERS
fi

if [[ -n $OVERRIDE_VAN_ETHSTATS_METRICS ]]; then
  VAN_ETHSTATS_METRICS=$OVERRIDE_VAN_ETHSTATS_METRICS
fi

if [[ -n $OVERRIDE_RUN_LUKSO_STATUS ]]; then
  RUN_LUKSO_STATUS=$OVERRIDE_RUN_LUKSO_STATUS
fi

if [[ -n $OVERRIDE_HTTP_CONNECTIVITY ]]; then
  HTTP_CONNECTIVITY=$OVERRIDE_HTTP_CONNECTIVITY
fi

if [[ -n $OVERRIDE_CUSTOM_GENESIS_TIME ]]; then
  CUSTOM_GENESIS_TIME=$OVERRIDE_CUSTOM_GENESIS_TIME
fi

if [[ -n $OVERRIDE_SECONDS_PER_SLOT ]]; then
  SECONDS_PER_SLOT=$OVERRIDE_SECONDS_PER_SLOT
fi

if [[ ! -d $DATADIR ]]; then
  mkdir -p $DATADIR
fi

if [[ ! -f $DATADIR/genesis-time.txt ]]; then
  echo -n $GENESIS_TIME > $DATADIR/genesis-time.txt
fi

if [[ $ALLOW_RESPIN ]]; then
  # Check if new genesis
  if [[ $(cat $DATADIR/genesis-time.txt) != $GENESIS_TIME ]]; then
    echo "New config received, resetting datadirs"
    reset all
    echo -n $GENESIS_TIME > $DATADIR/genesis-time.txt
  fi
fi

case $COMMAND in
start)
  start $COMMAND_ARG
  ;;
stop)
  stop $COMMAND_ARG
  ;;
reset)
  reset $COMMAND_ARG
  ;;
config)
  setup_config
  ;;
gen-deposit-data)
  generate_deposit_data
  ;;
keystore)
  generate_keystore
  ;;
logs)
  logs "$COMMAND_ARG"
  ;;
version)
  echo "$LUKSO_SCRIPT_VERSION"
  ;;
attach)
  geth attach $DATADIR/geth/geth.ipc
  ;;
bind-binaries) ;;

*)
  help
  exit 1
  ;;
esac
